# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/DBmanagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Protos/DBmanagement.proto\x12\ndb_manager\"k\n\x18MultiplicationParameters\x12&\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x17.db_manager.DataTableSO\x12\'\n\x06second\x18\x02 \x01(\x0b\x32\x17.db_manager.DataTableSO\"\x11\n\x0f\x43lientIdRequest\"F\n\x11\x44\x61taSavedResponce\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"*\n\x15\x43lientDataLookupModel\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"K\n\x0f\x43lientDataModel\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12%\n\x05\x62\x61ses\x18\x02 \x03(\x0b\x32\x16.db_manager.DataBaseSO\"O\n\nDataBaseSO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\'\n\x06tables\x18\x03 \x03(\x0b\x32\x17.db_manager.DataTableSO\"w\n\x0b\x44\x61taTableSO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12)\n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x18.db_manager.DataColumnSO\x12#\n\x04rows\x18\x04 \x03(\x0b\x32\x15.db_manager.DataRowSO\"4\n\x0c\x44\x61taColumnSO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0esupported_type\x18\x02 \x01(\t\"\x19\n\tDataRowSO\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t2\xea\x01\n\x0c\x44\x42management\x12G\n\x05GetID\x12\x1b.db_manager.ClientIdRequest\x1a!.db_manager.ClientDataLookupModel\x12I\n\x07GetData\x12!.db_manager.ClientDataLookupModel\x1a\x1b.db_manager.ClientDataModel\x12\x46\n\x08SaveData\x12\x1b.db_manager.ClientDataModel\x1a\x1d.db_manager.DataSavedResponce2r\n\x14OperationsManagement\x12Z\n\x19PerformFullMultiplication\x12$.db_manager.MultiplicationParameters\x1a\x17.db_manager.DataTableSOB\t\xaa\x02\x06Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.DBmanagement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\006Server'
  _globals['_MULTIPLICATIONPARAMETERS']._serialized_start=41
  _globals['_MULTIPLICATIONPARAMETERS']._serialized_end=148
  _globals['_CLIENTIDREQUEST']._serialized_start=150
  _globals['_CLIENTIDREQUEST']._serialized_end=167
  _globals['_DATASAVEDRESPONCE']._serialized_start=169
  _globals['_DATASAVEDRESPONCE']._serialized_end=239
  _globals['_CLIENTDATALOOKUPMODEL']._serialized_start=241
  _globals['_CLIENTDATALOOKUPMODEL']._serialized_end=283
  _globals['_CLIENTDATAMODEL']._serialized_start=285
  _globals['_CLIENTDATAMODEL']._serialized_end=360
  _globals['_DATABASESO']._serialized_start=362
  _globals['_DATABASESO']._serialized_end=441
  _globals['_DATATABLESO']._serialized_start=443
  _globals['_DATATABLESO']._serialized_end=562
  _globals['_DATACOLUMNSO']._serialized_start=564
  _globals['_DATACOLUMNSO']._serialized_end=616
  _globals['_DATAROWSO']._serialized_start=618
  _globals['_DATAROWSO']._serialized_end=643
  _globals['_DBMANAGEMENT']._serialized_start=646
  _globals['_DBMANAGEMENT']._serialized_end=880
  _globals['_OPERATIONSMANAGEMENT']._serialized_start=882
  _globals['_OPERATIONSMANAGEMENT']._serialized_end=996
# @@protoc_insertion_point(module_scope)
